
import { getAuth, initializeAuth, indexedDBLocalPersistence } from 'firebase/auth';
import { initializeApp } from "firebase/app";
import { User, BuddyRequest, StudyGroup, Message, ChatId, StudyPlan, Subject, HelpRequest, QuizEvent } from '../types';

// In a real app, these would be in a .env file
const firebaseConfig = {
  apiKey: "MOCK_API_KEY",
  authDomain: "MOCK_AUTH_DOMAIN",
  projectId: "MOCK_PROJECT_ID",
  storageBucket: "MOCK_STORAGE_BUCKET",
  messagingSenderId: "MOCK_MESSAGING_SENDER_ID",
  appId: "MOCK_APP_ID"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// This is a bit of a trick. In a browser environment for a demo,
// we can use the real Firebase JS SDK with local persistence.
// This gives us a realistic auth flow without needing a backend.
// It will use IndexedDB to store user sessions.
export const auth = initializeAuth(app, {
  persistence: indexedDBLocalPersistence
});


// --- MOCK DATABASE ---
const DB_KEY = 'studySphereMockDb';

interface Database {
  users: Record<string, User>;
  requests: Record<string, BuddyRequest>;
  groups: Record<string, StudyGroup>;
  messages: Record<string, Message[]>;
  plans: Record<string, StudyPlan>;
  helpRequests: Record<string, HelpRequest>;
}

let db: Database = {
    users: {},
    requests: {},
    groups: {},
    messages: {},
    plans: {},
    helpRequests: {}
};

// Helper to save state to localStorage
const saveDb = () => {
  try {
    localStorage.setItem(DB_KEY, JSON.stringify(db));
  } catch (e) {
    console.error("Failed to save mock DB to localStorage", e);
  }
};

// Helper to load state from localStorage
const loadDb = () => {
  try {
    const savedDb = localStorage.getItem(DB_KEY);
    if (savedDb) {
      db = JSON.parse(savedDb);
    } else {
        // Initialize with some data if the DB is empty
        initializeDemoData();
        saveDb();
    }
  } catch (e) {
    console.error("Failed to load mock DB from localStorage", e);
    initializeDemoData();
  }
};

const initializeDemoData = () => {
    // This function will be called if there's no data in localStorage
    // In a real mock setup for auth, we can't pre-populate users easily
    // because their IDs are generated by Firebase Auth.
    // So we'll let user creation happen through the signup flow.
    db = { users: {}, requests: {}, groups: {}, messages: {}, plans: {}, helpRequests: {} };
};

// Load the DB on module initialization
loadDb();


// --- API ---

// User Functions
export const createUserProfile = async (user: User): Promise<void> => {
  db.users[user.id] = user;
  saveDb();
};

export const getUserById = async (userId: string): Promise<User | null> => {
  return db.users[userId] || null;
};

export const getAllUsers = async (): Promise<User[]> => {
    return Object.values(db.users);
}

export const updateUser = async (user: User): Promise<void> => {
    db.users[user.id] = user;
    saveDb();
};


// Buddy & Request Functions
export const getBuddies = async (userId: string): Promise<User[]> => {
    const user = await getUserById(userId);
    if (!user) return [];
    
    // Buddies are defined by accepted requests where the user is either sender or receiver
    const buddyIds = new Set<string>();
    Object.values(db.requests).forEach(req => {
        if (req.status === 'accepted') {
            if (req.senderId === userId) buddyIds.add(req.receiverId);
            if (req.receiverId === userId) buddyIds.add(req.senderId);
        }
    });

    return Promise.all(Array.from(buddyIds).map(id => getUserById(id) as Promise<User>));
};


export const getBuddyRequestsForUser = async (userId: string): Promise<BuddyRequest[]> => {
    return Object.values(db.requests).filter(req => req.receiverId === userId && req.status === 'pending');
};

export const sendBuddyRequest = async (senderId: string, receiverId: string): Promise<void> => {
    // Check if a request already exists or if they are already buddies
    const existing = Object.values(db.requests).find(r => 
        (r.senderId === senderId && r.receiverId === receiverId) ||
        (r.senderId === receiverId && r.receiverId === senderId)
    );

    if (existing) {
        if (existing.status === 'accepted') throw new Error("You are already buddies.");
        if (existing.status === 'pending') throw new Error("A request is already pending.");
    }
    
    const id = `req_${Date.now()}`;
    db.requests[id] = {
        id,
        senderId,
        receiverId,
        status: 'pending',
        createdAt: new Date().toISOString()
    };
    saveDb();
};

export const respondToBuddyRequest = async (requestId: string, status: 'accepted' | 'declined'): Promise<void> => {
    if (db.requests[requestId]) {
        db.requests[requestId].status = status;
        saveDb();
    }
};

// Group Functions
export const getGroupsForUser = async (userId: string): Promise<StudyGroup[]> => {
    return Object.values(db.groups).filter(g => g.members.includes(userId));
};

export const getGroupById = async (groupId: string): Promise<StudyGroup | null> => {
    return db.groups[groupId] || null;
}

export const createGroup = async (name: string, createdBy: string, description: string | null): Promise<StudyGroup> => {
    const id = `group_${Date.now()}`;
    const newGroup: StudyGroup = {
        id,
        name,
        description,
        createdBy,
        members: [createdBy],
        createdAt: new Date().toISOString(),
        sharedPlans: []
    };
    db.groups[id] = newGroup;
    saveDb();
    return newGroup;
};

export const addUserToGroup = async (userId: string, groupId: string): Promise<void> => {
    const group = db.groups[groupId];
    if (group && !group.members.includes(userId)) {
        group.members.push(userId);
        saveDb();
    }
};

// Chat Functions
const getChatKey = (chatId: ChatId): string => {
    if (chatId.type === 'dm') {
        // Sort IDs to ensure consistency
        const ids = [auth.currentUser!.uid, chatId.userId].sort();
        return `dm_${ids[0]}_${ids[1]}`;
    }
    return `group_${chatId.groupId}`;
};

export const getMessages = async (chatId: ChatId): Promise<Message[]> => {
    const key = getChatKey(chatId);
    return db.messages[key] || [];
};

export const sendMessage = async (chatId: ChatId, senderId: string, content: string, quizEvent?: QuizEvent): Promise<Message> => {
    const key = getChatKey(chatId);
    if (!db.messages[key]) {
        db.messages[key] = [];
    }
    const message: Message = {
        id: `msg_${Date.now()}`,
        chatId: key,
        senderId,
        content,
        createdAt: new Date().toISOString(),
        quizEvent
    };
    db.messages[key].push(message);
    saveDb();
    return message;
};

// Study Plan Functions
export const createStudyPlan = async (ownerId: string, title: string, details: string): Promise<StudyPlan> => {
    const id = `plan_${Date.now()}`;
    const newPlan: StudyPlan = {
        id,
        ownerId,
        title,
        details,
        createdAt: new Date().toISOString()
    };
    db.plans[id] = newPlan;
    saveDb();
    return newPlan;
};

export const getStudyPlanById = async (planId: string): Promise<StudyPlan | null> => {
    return db.plans[planId] || null;
}

export const sharePlanWithGroup = async (planId: string, sharerId: string, groupId: string): Promise<void> => {
    const group = db.groups[groupId];
    const plan = db.plans[planId];
    if (group && plan && group.members.includes(sharerId)) {
        if (!group.sharedPlans) {
            group.sharedPlans = [];
        }
        if (!group.sharedPlans.includes(planId)) {
            group.sharedPlans.push(planId);
            saveDb();
        }
    } else {
        throw new Error("Could not share plan. Group, plan, or user permissions invalid.");
    }
};

// Help Request Functions
export const createHelpRequest = async (requesterId: string, subject: Subject, topic: string): Promise<HelpRequest> => {
    const id = `hr_${Date.now()}`;
    const newRequest: HelpRequest = {
        id,
        requesterId,
        subject,
        topic,
        createdAt: new Date().toISOString(),
        status: 'open',
    };
    db.helpRequests[id] = newRequest;
    saveDb();
    return newRequest;
};

export const getOpenHelpRequests = async (): Promise<HelpRequest[]> => {
    return Object.values(db.helpRequests)
        .filter(req => req.status === 'open')
        .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
};
